/* Generated by MyraPad at 8/31/2026 10:15:05 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace FontStashSharp.Samples
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_panelTextContainer = new Panel();
			_panelTextContainer.Id = "_panelTextContainer";

			_propertyGridTextSettings = new PropertyGrid();
			_propertyGridTextSettings.Id = "_propertyGridTextSettings";

			_splitPaneTop = new HorizontalSplitPane();
			_splitPaneTop.Id = "_splitPaneTop";
			StackPanel.SetProportionType(_splitPaneTop, Myra.Graphics2D.UI.ProportionType.Fill);
			_splitPaneTop.Widgets.Add(_panelTextContainer);
			_splitPaneTop.Widgets.Add(_propertyGridTextSettings);

			var horizontalSeparator1 = new HorizontalSeparator();

			var label1 = new Label();
			label1.Text = "Font Size";

			_textFontSize = new SpinButton();
			_textFontSize.Maximum = 128;
			_textFontSize.Minimum = 4;
			_textFontSize.Value = 32;
			_textFontSize.Integer = true;
			_textFontSize.Width = 50;
			_textFontSize.Id = "_textFontSize";
			Grid.SetColumn(_textFontSize, 1);

			var label2 = new Label();
			label2.Text = "Scale";
			label2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetRow(label2, 1);

			_sliderScale = new HorizontalSlider();
			_sliderScale.Minimum = 1;
			_sliderScale.Maximum = 8;
			_sliderScale.Value = 3;
			_sliderScale.Width = 200;
			_sliderScale.Id = "_sliderScale";

			_labelScale = new Label();
			_labelScale.Text = "3";
			_labelScale.Id = "_labelScale";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel1, 1);
			Grid.SetRow(horizontalStackPanel1, 1);
			horizontalStackPanel1.Widgets.Add(_sliderScale);
			horizontalStackPanel1.Widgets.Add(_labelScale);

			var label3 = new Label();
			label3.Text = "Text";
			Grid.SetRow(label3, 2);

			_text = new TextBox();
			_text.Text = "Hello, World!";
			_text.Multiline = true;
			_text.Height = 100;
			_text.Id = "_text";
			Grid.SetColumn(_text, 1);
			Grid.SetRow(_text, 2);

			var label4 = new Label();
			label4.Text = "Color";
			Grid.SetRow(label4, 3);

			var label5 = new Label();
			label5.Text = "Text Style";
			Grid.SetRow(label5, 4);

			var label6 = new Label();
			label6.Text = "Change...";

			_buttonChangeColor = new Button();
			_buttonChangeColor.Id = "_buttonChangeColor";
			Grid.SetColumn(_buttonChangeColor, 1);
			Grid.SetRow(_buttonChangeColor, 3);
			_buttonChangeColor.Content = label6;

			var label7 = new Label();
			label7.Text = "None";

			var label8 = new Label();
			label8.Text = "Underline";

			var label9 = new Label();
			label9.Text = "Strikethrough";

			_comboTextStyle = new ComboView();
			_comboTextStyle.Id = "_comboTextStyle";
			Grid.SetColumn(_comboTextStyle, 1);
			Grid.SetRow(_comboTextStyle, 4);
			_comboTextStyle.Widgets.Add(label7);
			_comboTextStyle.Widgets.Add(label8);
			_comboTextStyle.Widgets.Add(label9);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_textFontSize);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(horizontalStackPanel1);
			grid1.Widgets.Add(label3);
			grid1.Widgets.Add(_text);
			grid1.Widgets.Add(label4);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(_buttonChangeColor);
			grid1.Widgets.Add(_comboTextStyle);

			
			Widgets.Add(_splitPaneTop);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(grid1);
		}

		
		private Panel _panelTextContainer;
		private PropertyGrid _propertyGridTextSettings;
		private HorizontalSplitPane _splitPaneTop;
		private SpinButton _textFontSize;
		private HorizontalSlider _sliderScale;
		private Label _labelScale;
		private TextBox _text;
		private Button _buttonChangeColor;
		private ComboView _comboTextStyle;
	}
}
