<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Input" Version="2.15.0" />
    <PackageReference Include="Silk.NET.OpenGL" Version="2.15.0" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.15.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Fonts\DroidSans.ttf" Link="Assets\Fonts\DroidSans.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Fonts\DroidSansJapanese.ttf" Link="Assets\Fonts\DroidSansJapanese.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Fonts\Symbola-Emoji.ttf" Link="Assets\Fonts\Symbola-Emoji.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <ProjectReference Include="..\..\src\FontStashSharp\FontStashSharp.PlatformAgnostic.csproj" />
    <None Update="Assets\Shaders\shader.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\shader.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\sdf.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>