/* Generated by MyraPad at 9/16/2026 11:35:34 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Styles;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace FontStashSharp.Tool.UI
{
	partial class MainPanel: VerticalSplitPane
	{
		private void BuildUI()
		{
			_panelTextContainer = new Panel();
			_panelTextContainer.Id = "_panelTextContainer";

			_propertyGridTextSettings = new PropertyGrid();
			_propertyGridTextSettings.Id = "_propertyGridTextSettings";

			var scrollViewer1 = new ScrollViewer();
			StackPanel.SetProportionType(scrollViewer1, Myra.Graphics2D.UI.ProportionType.Part);
			scrollViewer1.Content = _propertyGridTextSettings;

			_panelRight = new VerticalStackPanel();
			_panelRight.Id = "_panelRight";
			_panelRight.Widgets.Add(scrollViewer1);

			_panelTop = new HorizontalSplitPane();
			_panelTop.Id = "_panelTop";
			_panelTop.Widgets.Add(_panelTextContainer);
			_panelTop.Widgets.Add(_panelRight);

			var label1 = new Label();
			label1.Text = "Font";

			_textFontFile = new TextBox();
			_textFontFile.Readonly = true;
			_textFontFile.Width = 300;
			_textFontFile.Id = "_textFontFile";

			var label2 = new Label();
			label2.Text = "Browse...";

			_buttonBrowseFont = new Button();
			_buttonBrowseFont.Id = "_buttonBrowseFont";
			_buttonBrowseFont.Content = label2;

			var label3 = new Label();
			label3.Text = "Reset";

			_buttonResetFont = new Button();
			_buttonResetFont.Id = "_buttonResetFont";
			_buttonResetFont.Content = label3;

			var label4 = new Label();
			label4.Text = "Size";

			_spinButtonFontSize = new SpinButton();
			_spinButtonFontSize.Maximum = 128;
			_spinButtonFontSize.Minimum = 4;
			_spinButtonFontSize.Value = 32;
			_spinButtonFontSize.Integer = true;
			_spinButtonFontSize.Width = 50;
			_spinButtonFontSize.Id = "_spinButtonFontSize";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel1, 1);
			horizontalStackPanel1.Widgets.Add(_textFontFile);
			horizontalStackPanel1.Widgets.Add(_buttonBrowseFont);
			horizontalStackPanel1.Widgets.Add(_buttonResetFont);
			horizontalStackPanel1.Widgets.Add(label4);
			horizontalStackPanel1.Widgets.Add(_spinButtonFontSize);

			var label5 = new Label();
			label5.Text = "Scale";
			label5.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			Grid.SetRow(label5, 1);

			_sliderScale = new HorizontalSlider();
			_sliderScale.Minimum = 1;
			_sliderScale.Maximum = 8;
			_sliderScale.Value = 3;
			_sliderScale.Width = 200;
			_sliderScale.Id = "_sliderScale";

			_labelScale = new Label();
			_labelScale.Text = "3";
			_labelScale.Id = "_labelScale";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel2, 1);
			Grid.SetRow(horizontalStackPanel2, 1);
			horizontalStackPanel2.Widgets.Add(_sliderScale);
			horizontalStackPanel2.Widgets.Add(_labelScale);

			var label6 = new Label();
			label6.Text = "Text";
			Grid.SetRow(label6, 2);

			_text = new TextBox();
			_text.Text = "Plain text./n/dsShadow text./dd/n/dtStroked text.";
			_text.Multiline = true;
			_text.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_text.Id = "_text";
			Grid.SetColumn(_text, 1);
			Grid.SetRow(_text, 2);

			var label7 = new Label();
			label7.Text = "Show Texture";

			_checkShowTexture = new CheckButton();
			_checkShowTexture.CheckContentSpacing = 8;
			_checkShowTexture.Id = "_checkShowTexture";
			Grid.SetRow(_checkShowTexture, 3);
			Grid.SetColumnSpan(_checkShowTexture, 2);
			_checkShowTexture.Content = label7;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			
			
			
			grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});grid1.RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(horizontalStackPanel1);
			grid1.Widgets.Add(label5);
			grid1.Widgets.Add(horizontalStackPanel2);
			grid1.Widgets.Add(label6);
			grid1.Widgets.Add(_text);
			grid1.Widgets.Add(_checkShowTexture);

			var horizontalSplitPane1 = new HorizontalSplitPane();
			horizontalSplitPane1.Widgets.Add(grid1);

			
			Id = "_panelRoot";
			Widgets.Add(_panelTop);
			Widgets.Add(horizontalSplitPane1);
		}

		
		private Panel _panelTextContainer;
		private PropertyGrid _propertyGridTextSettings;
		private VerticalStackPanel _panelRight;
		private HorizontalSplitPane _panelTop;
		private TextBox _textFontFile;
		private Button _buttonBrowseFont;
		private Button _buttonResetFont;
		private SpinButton _spinButtonFontSize;
		private HorizontalSlider _sliderScale;
		private Label _labelScale;
		private TextBox _text;
		private CheckButton _checkShowTexture;
	}
}
