<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <PackageId>FontStashSharp.Kni</PackageId>
    <AssemblyName>FontStashSharp.Kni</AssemblyName>
    <Description>FontStashSharp for Kni</Description>
    <DefineConstants>$(DefineConstants);KNI</DefineConstants>
    <OutputPath>bin\Kni\$(Configuration)</OutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FontStashSharp.Base" Version="$(FontStashSharpBaseVersion)" />
    <PackageReference Include="FontStashSharp.Rasterizers.StbTrueTypeSharp" Version="$(FontStashSharpBaseVersion)" />
    <PackageReference Include="Cyotek.Drawing.BitmapFont" Version="$(CyotekDrawingBitmapFontVersion)" />
    <PackageReference Include="nkast.Xna.Framework.Graphics" Version="$(KniVersion)" />
    <PackageReference Include="StbImageSharp" Version="$(StbImageSharpVersion)" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\FontStashSharp\**\*.cs" LinkBase="FontStashSharp" />
    <Compile Remove="..\FontStashSharp\obj\**\*.cs" LinkBase="FontStashSharp" />
  </ItemGroup>
</Project>
