<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(AppTargetFramework)</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <RootNamespace>FontStashSharp.Tool</RootNamespace>
    <AssemblyName>FontStashSharp.Tool</AssemblyName>
    <PackageId>fss-tool</PackageId>
    <ToolCommandName>fss-tool</ToolCommandName>
    <OutputPath>bin\MonoGame\$(Configuration)</OutputPath>
    <DefineConstants>$(DefineConstants);MONOGAME</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(AppMonoGameVersion)" />
    <PackageReference Include="Myra" Version="1.6.6" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\**\*.*" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\XNA\FontStashSharp.MonoGame.csproj" />
  </ItemGroup>  
</Project>