/* Generated by MyraPad at 6/26/2021 3:40:09 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace FontStashSharp.Samples.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Font Resolution Factor:";

			_spinButtonFontResolutionFactor = new SpinButton();
			_spinButtonFontResolutionFactor.Value = 2;
			_spinButtonFontResolutionFactor.Width = 50;
			_spinButtonFontResolutionFactor.Id = "_spinButtonFontResolutionFactor";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(_spinButtonFontResolutionFactor);

			var verticalSeparator1 = new VerticalSeparator();

			var label2 = new Label();
			label2.Text = "Kernel Width:";

			_spinButtonKernelWidth = new SpinButton();
			_spinButtonKernelWidth.Value = 2;
			_spinButtonKernelWidth.Integer = true;
			_spinButtonKernelWidth.Width = 50;
			_spinButtonKernelWidth.Id = "_spinButtonKernelWidth";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(label2);
			horizontalStackPanel2.Widgets.Add(_spinButtonKernelWidth);

			var verticalSeparator2 = new VerticalSeparator();

			var label3 = new Label();
			label3.Text = "Kernel Height:";

			_spinButtonKernelHeight = new SpinButton();
			_spinButtonKernelHeight.Value = 2;
			_spinButtonKernelHeight.Integer = true;
			_spinButtonKernelHeight.Width = 50;
			_spinButtonKernelHeight.Id = "_spinButtonKernelHeight";

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Spacing = 8;
			horizontalStackPanel3.Widgets.Add(label3);
			horizontalStackPanel3.Widgets.Add(_spinButtonKernelHeight);

			var verticalSeparator3 = new VerticalSeparator();

			var label4 = new Label();
			label4.Text = "Scale:";

			_spinButtonScale = new SpinButton();
			_spinButtonScale.Value = 2;
			_spinButtonScale.Width = 50;
			_spinButtonScale.Id = "_spinButtonScale";

			var horizontalStackPanel4 = new HorizontalStackPanel();
			horizontalStackPanel4.Spacing = 8;
			horizontalStackPanel4.Widgets.Add(label4);
			horizontalStackPanel4.Widgets.Add(_spinButtonScale);

			var horizontalStackPanel5 = new HorizontalStackPanel();
			horizontalStackPanel5.Widgets.Add(horizontalStackPanel1);
			horizontalStackPanel5.Widgets.Add(verticalSeparator1);
			horizontalStackPanel5.Widgets.Add(horizontalStackPanel2);
			horizontalStackPanel5.Widgets.Add(verticalSeparator2);
			horizontalStackPanel5.Widgets.Add(horizontalStackPanel3);
			horizontalStackPanel5.Widgets.Add(verticalSeparator3);
			horizontalStackPanel5.Widgets.Add(horizontalStackPanel4);

			var horizontalSeparator1 = new HorizontalSeparator();

			_panelTopContainer = new Panel();
			_panelTopContainer.Id = "_panelTopContainer";

			var horizontalSeparator2 = new HorizontalSeparator();

			_panelBottomContainer = new Panel();
			_panelBottomContainer.Id = "_panelBottomContainer";

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			Widgets.Add(horizontalStackPanel5);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(_panelTopContainer);
			Widgets.Add(horizontalSeparator2);
			Widgets.Add(_panelBottomContainer);
		}

		
		public SpinButton _spinButtonFontResolutionFactor;
		public SpinButton _spinButtonKernelWidth;
		public SpinButton _spinButtonKernelHeight;
		public SpinButton _spinButtonScale;
		public Panel _panelTopContainer;
		public Panel _panelBottomContainer;
	}
}
